
set(libOTe_VERSION_MAJOR     2)
set(libOTe_VERSION_MINOR     0)
set(libOTe_VERSION_PATCH     4)

unset(libOTe_debug_FOUND CACHE)
unset(libOTe_Debug_FOUND CACHE)
unset(libOTe_DEBUG_FOUND CACHE)
unset(libOTe_release_FOUND CACHE)
unset(libOTe_Release_FOUND CACHE)
unset(libOTe_RELEASE_FOUND CACHE)
unset(libOTe_relwithdebinfo_FOUND CACHE)
unset(libOTe_RelWithDebInfo_FOUND CACHE)
unset(libOTe_RELWITHDEBINFO_FOUND CACHE)

set(LIBOTE_BUILD_TYPE "Release")
string( TOLOWER "Release" CMAKE_BUILD_TYPE_lower )
if(CMAKE_BUILD_TYPE_lower STREQUAL "debug")
	set(libOTe_debug_FOUND true)
	set(libOTe_Debug_FOUND true)
	set(libOTe_DEBUG_FOUND true)
endif()
if(CMAKE_BUILD_TYPE_lower STREQUAL "release")
	set(libOTe_release_FOUND true)
	set(libOTe_Release_FOUND true)
	set(libOTe_RELEASE_FOUND true)
endif()
if(CMAKE_BUILD_TYPE_lower STREQUAL "relwithdebinfo")
	set(libOTe_relwithdebinfo_FOUND true)
	set(libOTe_RelWithDebInfo_FOUND true)
	set(libOTe_RELWITHDEBINFO_FOUND true)
endif()


set(LIBOTE_STD_VER 17)
set(CRYPTO_TOOLS_STD_VER 17)
set(libOTe_std_14_FOUND false)
set(libOTe_std_17_FOUND false)
set(libOTe_std_20_FOUND false)
set(libOTe_std_17_FOUND true)


set(ENABLE_BITPOLYMUL		ON)
set(ENABLE_BOOST			ON)
set(ENABLE_RELIC			OFF)
set(ENABLE_SODIUM			ON)
set(ENABLE_COPROTO			true)

set(ENABLE_OPENSSL			OFF)
set(ENABLE_CIRCUITS			ON)
set(ENABLE_SSE				ON)
set(ENABLE_AVX				ON)
set(ENABLE_PIC				OFF)
set(ENABLE_ASAN				OFF)
set(SODIUM_MONTGOMERY       ON)

set(ENABLE_SIMPLESTOT     OFF)
set(ENABLE_SIMPLESTOT_ASM OFF)
set(ENABLE_MRR            ON)
set(ENABLE_MRR_TWIST      OFF)
set(ENABLE_MR             OFF)
set(ENABLE_MR_KYBER       OFF)
set(ENABLE_KOS            OFF)
set(ENABLE_IKNP           ON)
set(ENABLE_SOFTSPOKEN_OT  ON)
set(ENABLE_SILENTOT       ON)
set(ENABLE_DELTA_KOS      OFF)
set(ENABLE_OOS            OFF)
set(ENABLE_KKRT           OFF)
set(ENABLE_SILENT_VOLE    ON)
set(NO_SILVER_WARNING     OFF)


set(libOTe_boost_FOUND		ON)
set(libOTe_relic_FOUND		OFF)
set(libOTe_sodium_FOUND		ON)
set(libOTe_bitpolymul_FOUND ON)
set(libOTe_openssl_FOUND	OFF)
set(libOTe_sodium_montgomery_FOUND	ON)

set(libOTe_circuits_FOUND	ON)
set(libOTe_sse_FOUND		ON)
set(libOTe_avx_FOUND		ON)
set(libOTe_asan_FOUND		OFF)
set(libOTe_pic_FOUND		OFF)

if(ENABLE_SSE)
	set(libOTe_no_sse_FOUND false)
else()
	set(libOTe_no_sse_FOUND true)
endif()

if(ENABLE_AVX)
	set(libOTe_no_avx_FOUND false)
else()
	set(libOTe_no_avx_FOUND true)
endif()
if(ENABLE_PIC)
	set(libOTe_no_pic_FOUND false)
else()
	set(libOTe_no_pic_FOUND true)
endif()
if(ENABLE_ASAN)
	set(libOTe_no_asan_FOUND false)
else()
	set(libOTe_no_asan_FOUND true)
endif()

if(SODIUM_MONTGOMERY)
	set(libOTe_no_sodium_montgomery_FOUND false)
else()
	set(libOTe_no_sodium_montgomery_FOUND true)
endif()

set(libOTe_simplestot_FOUND		OFF)
set(libOTe_simplestot_asm_FOUND OFF)
set(libOTe_mrr_FOUND			ON)
set(libOTe_mrr_twist_FOUND		OFF)
set(libOTe_mr_FOUND				OFF)
set(libOTe_mr_kyber_FOUND		OFF)
set(libOTe_kos_FOUND			OFF)
set(libOTe_iknp_FOUND			ON)
set(libOTe_silentot_FOUND		ON)
set(libOTe_softspoken_ot_FOUND	ON)
set(libOTe_delta_kos_FOUND		OFF)
set(libOTe_silent_vole_FOUND	ON)
set(libOTe_oos_FOUND			OFF)
set(libOTe_kkrt_FOUND			OFF)


